# @package _global_
model:
  use_context: true
  context_mode: beat
  context_fuse: attn
  context_bars: 4
  beats_per_bar: 4
  beat_sigma_frames: 6
  add_tempo_features: false
training:
  notes: BeatContextAttn
