# config/experiment_T5_V5_BeatBarContext.yaml
defaults:
  - experiment_T5_V0

model:
  use_context: true
  context_mode: beat_bar   # beat | bar | beat_bar
  context_bars: 4
  beats_per_bar: 4
  beat_sigma_frames: 6
  add_tempo_features: false
  context_fuse: concat

training:
  notes: "BeatBarContext"

data:
  n_frames: 512
  max_token_length: 1024
  # dataset_dir: /nvme1/ray/maestro-v3.0.0
  # dataset_dirs: [/nvme1/ray/maestro-v3.0.0]