defaults:
  # - main_config

  # - experiment_T5_V0
  # - experiment_T5_V1_LocalEncAttn
  # - experiment_T5_V2_LocalEncDecAttn
  # - experiment_T5_V3_HybridGlobalLocalCrossAttn
  - experiment_T5_V4_HierarchyPool


# --config-name=experiment_T5_V0
# --config-name=experiment_T5_V1_LocalEncAttn
# --config-name=experiment_T5_V2_LocalEncDecAttn
# --config-name=experiment_T5_V3_HybridGlobalLocalCrossAttn
# --config-name=experiment_T5_V4_HierarchyPool

